import js from '@eslint/js';
import vue from 'eslint-plugin-vue';
import babelParser from '@babel/eslint-parser';
import prettierConfig from '@vue/eslint-config-prettier';

const typescriptParserOptions = {
  requireConfigFile: false,
  babelOptions: {
    plugins: ['@babel/plugin-syntax-typescript'],
  },
  ecmaVersion: 'latest',
  sourceType: 'module',
};

export default [
  js.configs.recommended,
  ...vue.configs['flat/recommended'],
  prettierConfig,
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vue.parser,
      parserOptions: {
        parser: babelParser,
        ecmaVersion: 'latest',
        sourceType: 'module',
        requireConfigFile: false,
        babelOptions: {
          plugins: ['@babel/plugin-syntax-typescript'],
        },
        extraFileExtensions: ['.vue'],
      },
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        MouseEvent: 'readonly',
        DragEvent: 'readonly',
        KeyboardEvent: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLAudioElement: 'readonly',
        HTMLIFrameElement: 'readonly',
        DOMRect: 'readonly',
        Node: 'readonly',
        Text: 'readonly',
        NodeFilter: 'readonly',
        FileReader: 'readonly',
        ProgressEvent: 'readonly',
        IntersectionObserver: 'readonly',
        Element: 'readonly',
        EventListener: 'readonly',
        WheelEvent: 'readonly',
        localStorage: 'readonly',
        File: 'readonly',
        Blob: 'readonly',
        Image: 'readonly',
        ClipboardItem: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        // Node.js globals (for config files)
        process: 'readonly',
        global: 'readonly',
        NodeJS: 'readonly',
        // Custom globals
        ga: 'readonly', // Google Analytics
        Capacitor: 'readonly',
        chrome: 'readonly',
        cordova: 'readonly',
      },
    },
    rules: {
      'vue/multi-word-component-names': 'off',
      'no-undef': 'off',
      'no-unused-vars': 'off',
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: babelParser,
      parserOptions: typescriptParserOptions,
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        MouseEvent: 'readonly',
        DragEvent: 'readonly',
        KeyboardEvent: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLImageElement: 'readonly',
        Node: 'readonly',
        Text: 'readonly',
        NodeFilter: 'readonly',
        FileReader: 'readonly',
        ProgressEvent: 'readonly',
        IntersectionObserver: 'readonly',
        Element: 'readonly',
        localStorage: 'readonly',
        File: 'readonly',
        Blob: 'readonly',
        Image: 'readonly',
        ClipboardItem: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        // Node.js globals (for config files)
        process: 'readonly',
        global: 'readonly',
        NodeJS: 'readonly',
        // Custom globals
        ga: 'readonly', // Google Analytics
        Capacitor: 'readonly',
        chrome: 'readonly',
        cordova: 'readonly',
      },
    },
    rules: {
      'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
      'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
      'no-undef': 'off',
      'no-unused-vars': 'off',
    },
  },
  {
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        Buffer: 'readonly',
        console: 'readonly',
        process: 'readonly',
      },
    },
  },
  {
    ignores: [
      'node_modules/',
      'dist/',
      'build/',
      '.vite/',
      '*.min.js',
      '*.config.js',
      '*.config.ts',
      'wailsjs/',
      'src/wailsjs/',
      'cypress/',
      'public/',
      'bindings/',
    ],
  },
];
