import type { TabName } from '@/types/settings';

// Keep Settings search limited to labels that are rendered without opening a
// dependent control. Status, error, confirmation, placeholder and modal copy
// deliberately stay out of the index.
export const settingsSearchKeys: Record<TabName, string[]> = {
  general: [
    'setting.general.application',
    'setting.general.startupOnBoot',
    'setting.general.closeToTray',
    'setting.general.theme',
    'setting.general.language',
    'setting.general.uiFontFamily',
    'setting.general.uiFontSize',
    'setting.update.updates',
    'setting.update.updateCheckEnabled',
    'setting.feed.refreshMode',
    'setting.database.dataManagement',
    'setting.database.dataDirectory',
    'setting.database.autoCleanup',
    'setting.database.mediaCacheEnabled',
    'setting.database.articleContentCacheCleanup',
    'setting.database.mediaCacheCleanup',
  ],
  reading: [
    'setting.tab.articleDisplay',
    'setting.reading.dateFormat',
    'setting.reading.timeFormat',
    'setting.reading.relativeTime',
    'setting.reading.defaultViewMode',
    'setting.reading.showArticlePreviewImages',
    'setting.reading.showFloatingToc',
    'setting.reading.showUnreadCounts',
    'setting.typography.layoutMode',
    'setting.tab.contentSettings',
    'setting.feed.enableFullTextFetch',
    'setting.reading.imageGalleryEnabled',
    'setting.tab.interactionSettings',
    'setting.reading.hoverMarkAsRead',
    'setting.reading.scrollMarkAsRead',
    'setting.reading.confirmMarkAsRead',
    'setting.reading.autoMarkRead',
    'setting.reading.rememberArticlePosition',
    'setting.reading.showHiddenArticles',
    'setting.tab.typography',
    'setting.typography.contentFontFamily',
    'setting.typography.contentFontSize',
    'setting.typography.contentLineHeight',
    'setting.tab.customization',
    'setting.customization.css',
  ],
  feeds: [
    'modal.feed.manageFeeds',
    'setting.feed.addFeed',
    'modal.tag.manageTags',
    'modal.discovery.feedDiscovery',
    'modal.discovery.discoverAllFeeds',
    'setting.database.dataManagement',
    'modal.opml.import',
    'modal.opml.export',
    'setting.database.cleanDatabase',
  ],
  content: [
    'setting.content.summary',
    'setting.content.enableSummary',
    'setting.content.translation',
    'setting.content.enableTranslation',
  ],
  ai: [
    'setting.ai.aiProfiles',
    'setting.ai.addProfile',
    'setting.ai.aiFeatures',
    'setting.ai.aiSearchEnabled',
    'setting.ai.aiChatEnabled',
    'setting.ai.aiUsage',
    'setting.ai.setUsageLimit',
  ],
  rules: [
    'modal.rule.rules',
    'setting.rule.addRule',
    'setting.rule.importRules',
    'setting.rule.exportRules',
  ],
  network: [
    'setting.network.proxySettings',
    'setting.network.enableProxy',
    'modal.feed.refreshSettings',
    'setting.feed.retryTimeout',
    'setting.network.networkSettings',
    'setting.network.reDetectNetwork',
  ],
  plugins: [
    'setting.rsshub.enabled',
    'setting.freshrss.integration',
    'setting.plugins.notion.integration',
    'setting.plugins.obsidian.integration',
    'setting.plugins.siyuan.integration',
    'setting.plugins.zotero.integration',
  ],
  shortcuts: ['setting.shortcut.shortcuts', 'setting.shortcut.shortcutsEnabled'],
  statistics: [
    'setting.statistic.statistics',
    'setting.statistic.articlesRead',
    'setting.statistic.articlesViewed',
    'setting.statistic.articlesFavorited',
    'setting.statistic.aiSummaries',
    'setting.statistic.aiChats',
  ],
  about: ['setting.about.version', 'setting.about.viewOnGitHub', 'setting.update.checkForUpdates'],
};
